services:
  db:
    image: postgres:15
    container_name: tortoise_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: tortoise
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: tortoise_app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:senha123@db:5432/tortoise"
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
